### ISSUE TITLE
not related but app.evervault.com fails to load when using github

### ISSUE THREAD

**Issue by statusunknown418** [evervault/evervault-node#168]
there's a weird behavior going on at least for me when trying to log in using github

 
<img width="822" alt="Screenshot 2024-01-16 at 19 11 01" src="https://github.com/evervault/evervault-node/assets/74371045/d6be3aae-2755-4e99-b396-209cfa90437b">

Reloading/trying again doesn't fix the issue and neither signing out/in

After inspecting the requests I see this
```json
{
    "statusCode": 409,
    "message": "The provided data is not unique",
    "code": "unique-validation-error"
}
```
probably related to the auth library being used

**Comment by boilsquid2** [comment]
> there's a weird behavior going on at least for me when trying to log in using github
> 
> <img alt="Screenshot 2024-01-16 at 19 11 01" width="822" src="https://private-user-images.githubusercontent.com/74371045/297222013-d6be3aae-2755-4e99-b396-209cfa90437b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODIxODUsIm5iZiI6MTcwNTQ4MTg4NSwicGF0aCI6Ii83NDM3MTA0NS8yOTcyMjIwMTMtZDZiZTNhYWUtMjc1NS00ZTk5LWIzOTYtMjA5Y2ZhOTA0MzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OGQ1ZThkMTVkMDRlMDZlNTg4ZTk4ZWViYzA1MjhjMGJmOTMxM2IwMzA4MmJmNTczN2Q0ODM2YzRjNmZjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1DlJCYzD2T7McsbsypVFyWRtzUQoj9lKRqB83S9Hj8">
> Reloading/trying again doesn't fix the issue and neither signing out/in
> 
> After inspecting the requests I see this
> 
> ```json
> {
>     "statusCode": 409,
>     "message": "The provided data is not unique",
>     "code": "unique-validation-error"
> }
> ```
> 
> probably related to the auth library being used

Hey @statusunknown418 I will take a look at this for you!

**Comment by boilsquid** [comment]
> there's a weird behavior going on at least for me when trying to log in using github
> 
> <img alt="Screenshot 2024-01-16 at 19 11 01" width="822" src="https://private-user-images.githubusercontent.com/74371045/297222013-d6be3aae-2755-4e99-b396-209cfa90437b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODU4ODAsIm5iZiI6MTcwNTQ4NTU4MCwicGF0aCI6Ii83NDM3MTA0NS8yOTcyMjIwMTMtZDZiZTNhYWUtMjc1NS00ZTk5LWIzOTYtMjA5Y2ZhOTA0MzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA5NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMzEyNGI2ZDUxZWNhZmMzMjE0OTMwM2FkYTFmOTYyMWI4NWE1MTRiNjA2MDFiNWNmYWU1MDc2NTk1YTIxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5pDA8QvPe58ljZ0GqEduIVoWTNq4TppOGVcpGp5KN4U">
> Reloading/trying again doesn't fix the issue and neither signing out/in
> 
> After inspecting the requests I see this
> 
> ```json
> {
>     "statusCode": 409,
>     "message": "The provided data is not unique",
>     "code": "unique-validation-error"
> }
> ```
> 
> probably related to the auth library being used

Hey @statusunknown418 looking into this for you now!
